- hosts: localhost

  vars:
    nuage_auth:
      api_username: csproot
      api_password: csproot
      api_enterprise: csp
      api_url: https://124.252.253.248:8443
      api_version: v4_0
    enterprise_name: OpenStack_default
    domain_itau: "test_domain_01"
    nuage_ingress_policy_to_find: "Ingress_priority_10"

  pre_tasks:

    - name: Read ACL entries settings from file
      include_vars: cfg/itau_regras_01/regras02.yml

  tasks:

    - name: Finding Enterprise
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: Enterprise
        command: find
        properties:
          name: "{{ enterprise_name }}"
      register: nuage_enterprise

    - name: Finding Domain
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: Domain
        parent_id: "{{ nuage_enterprise.id }}"
        parent_type: Enterprise
        command: find
        properties:
          name: "{{ domain_itau }}"
      register: nuage_dom

    - name: Finding ingress policy ACL template
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: IngressACLTemplate
        parent_id: "{{ nuage_dom.id }}"
        parent_type: Domain
        command: find
        properties:
          name: "{{ nuage_ingress_policy_to_find }}"
      register: nuage_ingress_policy

    - name: Create ACL entry
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: IngressACLEntryTemplate
        parent_id: "{{ nuage_ingress_policy.id }}"
        parent_type: IngressACLTemplate
        state: "{{ nuage_state }}"
        match_filter: "description == 'Itau_Ansible_{{ item.priority }}'"
        properties:
          action: "{{ item.action }}"
          description: "Itau_Ansible_{{ item.priority }}"
          ether_type: "0x0800"
          destination_port: "{{ item.destination_port }}"
          location_type: "{{ item.location_type }}"
          network_type: "{{ item.network_type }}"
          priority: "{{ item.priority }}"
          protocol: "{{ item.protocol }}"
          source_port: "*"
      with_items: "{{ nuage_acl_entries }}"
    
