- hosts: localhost

  vars:
    nuage_auth:
      api_username: csproot
      api_password: csproot
      api_enterprise: csp
      api_url: https://124.252.253.248:8443
      api_version: v4_0

  pre_tasks:

    - name: Read ACL entries settings from file
      include_vars: cfg/itau_regras_01/regras02.yml

  tasks:

    - name: Finding Enterprise
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: Enterprise
        command: find
        properties:
          name: "{{ enterprise_name }}"
      register: nuage_enterprise

    - name: Finding Domain
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: Domain
        parent_id: "{{ nuage_enterprise.id }}"
        parent_type: Enterprise
        command: find
        properties:
          name: "{{ nuage_domain }}"
      register: nuage_dom_reg

    - name: Finding Policy Group
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: PolicyGroup
        parent_id: "{{ nuage_dom_reg.id }}"
        parent_type: Domain
        command: find
        properties:
          name: "{{ nuage_pgroup }}"
      register: nuage_pg_reg

    - name: Get VMs from domain
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: VM
        parent_id: "{{ nuage_dom_reg.id }}"
        parent_type: Domain
        match_filter: "name == 'instance-0000000f'"
        command: find
      register: vm_array_reg

    - debug:
        var: vm_array_reg
