- hosts: localhost

  vars:
    nuage_auth:
      api_username: csproot
      api_password: csproot
      api_enterprise: csp
      api_url: https://124.252.253.248:8443
      api_version: v4_0
    enterprise_name: OpenStack_default
    domain_template_itau: "test_domain"

  tasks:

    - name: Finding Enterprise
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: Enterprise
        command: find
        properties:
          name: "{{ enterprise_name }}"
      register: nuage_enterprise

    - name: Finding DomainTemplate
      connection: local
      nuage_vspk:
        auth: "{{ nuage_auth }}"
        type: DomainTemplate
        parent_id: "{{ nuage_enterprise.id }}"
        parent_type: Enterprise
        command: find
        properties:
          name: "{{ domain_template_itau }}"
      register: nuage_dom_temp


    - debug:
        var: nuage_enterprise

    - debug:
        var: nuage_dom_temp

